In [ ]:
import numpy as np

l=[1,2,3,4,5]
arr = np.array(l)

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.fromfunction(lambda i,j:i==j,(3,3))


In [ ]:
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr1 = np.fromfunction(lambda i,j:i*j,(3,3))


In [ ]:
arr1

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
# 3 dimensional array
arr = np.zeros((1,3,3))

In [ ]:
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
arr1 =([1,2,3])
arr2=([4,5,6])
arr1+arr2

[1, 2, 3, 4, 5, 6]

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
l = [1,2,3,4]
s = pd.Series(l)

In [ ]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s[0:1]

0    1
dtype: int64

In [ ]:
s[2:4]

2    3
3    4
dtype: int64

In [ ]:
s[2:5]

2    3
3    4
dtype: int64

In [ ]:
#series into dataframe
s=pd.Series([90,85,75], index=["marks1","marks2","marks3"])
s

marks1    90
marks2    85
marks3    75
dtype: int64

In [ ]:
d = pd.DataFrame(s)
d

0
marks1  90
marks2  85
marks3  75

In [ ]:
d["new coloumn"]="student name"
d

0   new coloumn
marks1  90  student name
marks2  85  student name
marks3  75  student name

In [ ]:
import pandas as pd

mydataset = {
    "cars " : ["swift","celerio","BMW"], "price" : [5000,3000,11000]
}
myvar = pd.DataFrame(mydataset)



In [ ]:
myvar

cars   price
0    swift   5000
1  celerio   3000
2      BMW  11000

In [ ]:
import pandas as pd
mydataset = {" calories intake" :[2000,2500,2700,2300,2400,2200,2100], " Days " :["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"] }

myvar = pd.DataFrame(mydataset,index=["day1","day2","day3","day4","day5","day6","day7"])


In [ ]:
myvar

calories intake      Days 
day1             2000     Monday
day2             2500    Tuesday
day3             2700  Wednesday
day4             2300   Thursday
day5             2400     Friday
day6             2200   Saturday
day7             2100     Sunday

In [ ]:
myvar.loc["day1"]

calories intake      2000
Days               Monday
Name: day1, dtype: object

# New section

In [5]:
import pandas as pd
df = pd.read_csv('submission.csv')
df


Unnamed: 0  data
0             0     0
1             1     1
2             2     2
3             3     3
4             4     4
..          ...   ...
995         995   995
996         996   996
997         997   997
998         998   998
999         999   999

[1000 rows x 2 columns]

In [ ]:
import numpy as np
print("1D Array")
arr1 = np.array([1,2,3])
arr1

1D Array


array([1, 2, 3])

In [ ]:
print("2D Array")
arr2 = np.array([[0,1,2],[3,4,5]])
arr2

2D Array


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print("3D Array")
arr3 = np.array([[[0,0,0,0],[1,1,1,1],[3,6,9,12]]])
arr3

3D Array


array([[[ 0,  0,  0,  0],
        [ 1,  1,  1,  1],
        [ 3,  6,  9, 12]]])

In [ ]:
#shape>> no. of rows and column in the array
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(1, 3, 4)


In [ ]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr4.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.arange(1,51)
a = a.reshape(10,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
#slicing in array
a[0]

array([1, 2, 3, 4, 5])

In [ ]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[6,4]

35

In [ ]:
a = np.arange(0,18).reshape(3,6)
b = np.arange(18,36).reshape(3,6)
print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
#addition

a+b

array([[18, 20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50, 52]])

In [ ]:
b-a

array([[18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18]])

In [ ]:
a.min()

0

In [ ]:
a.max()

17

In [ ]:
a.mean()

8.5

In [ ]:
np.median(a)



8.5

In [ ]:
# axix means rows and here sum of all rows is determined
np.sum(a,axis=1)

array([15, 51, 87])

In [ ]:
#axis means column
np.sum(a,axis=0)

array([18, 21, 24, 27, 30, 33])

In [11]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
array = np.reshape(array, (3, 3))  # Adjust the shape to match the total number of elements
print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
